---
title: "FR_crustacean"
author: "Maria Garcia"
date: "2024-02-22"
output: html_document
---

```{r}
source("library.R")
```

```{r}
epifauna<- read.csv(file="data/functional.epifauna.csv")
epifauna<- separate(epifauna, col=Site, into=c( 'Site','Zone', 'Number', 'Species'))
epifauna <- epifauna[-102, ]
epifauna$crustacean <- as.numeric(epifauna$crustacean)
epifauna$Zone <- factor(epifauna$Zone, levels = c("H", "M", "L"))

crust.mono <- filter(epifauna, Condition == "Mono")
crust.mono.anova<- aov(asin(sqrt(crustacean))~Site*Zone*Species, data = crust.mono)
summary(crust.mono.anova)
# glm.mono<- glm(cbind(sum.crust.int, sum.native.int )~Site * Zone* Species, data = crust.mono, family = "binomial") 
# summary(glm.mono)
# summary(aov(glm.mono))


crust.zm <- filter(epifauna, Species == "ZM")
crust.zm.anova<- aov(asin(sqrt(crustacean))~Site*Zone*Condition, data = crust.zm)
summary(crust.zm.anova)
# glm.zm<- glm(cbind(sum.crust.int, sum.native.int )~Site * Zone* Condition, data = crust.zm, family = "binomial") 
# summary(glm.zm)
# summary(aov(glm.zm))
 

crust.zj <- filter(epifauna, Species == "ZJ")
crust.zj.anova<- aov(asin(sqrt(crustacean))~ Site*Zone*Condition, data = crust.zj)
summary(crust.zj.anova)
# glm.zj<- glm(cbind(sum.crust.int, sum.native.int )~Site * Zone* Condition, data = crust.zj, family = "binomial") 
# anova(glm.zj)
# aov(glm.zj)
# summary(aov(glm.zj))
# 
# glm.zj.2<- glm(cbind(sum.crust.int, sum.native.int )~ Site*Zone + Site*Condition+ Zone*Condition, data = crust.zj, family = "binomial") 
# summary(glm.zj.2)
# 
# anova(glm.zj, glm.zj.2, test="Chisq")
```




```{r}

crust_mono_mean<- crust.mono%>%
  group_by(`Site`,`Zone`, `Species`)%>%
  summarise(mean = mean(crustacean, na.rm = T), n = length(crustacean)-sum(is.na(crustacean)), 
            sd = sd(crustacean, na.rm = T), se= sd/sqrt(n) )

g_crust<- ggplot(crust_mono_mean, aes(x=Zone, y= mean, group = Species))+geom_point(stat="identity", position= position_dodge(width = 0.5), aes(shape = Species), size = 2)+ geom_errorbar(aes(ymax = mean+se, ymin = mean-se, width= 0.5), position= position_dodge(0.5))+ geom_line(position= position_dodge(0.5), size=0.25, show.legend = FALSE)+ xlab("Zone")+ylab("Proportion of Crustaceans ")+ facet_grid(col= vars(Site))+  scale_x_discrete(labels=c("High", "Mid", "Low"))+ theme(axis.text.x = element_text(angle = 45, vjust = 0.75)) + scale_shape_manual(values= c(1,16), name = "Species Composition", labels = c("Zj monoculture","Zm monoculture"))+ theme_better + ylim(c(0,1.0))
plot(g_crust)

ggsave("figures/crust.mono.pdf",  width = 6.92, height = 4.27)
```

```{r}

crust_mono_mean$Species <- factor(crust_mono_mean$Species, levels = c("ZJ", "ZM"), labels = c("Non-native", "Native")) 
g_tot<- ggplot(crust_mono_mean, aes(x=Zone, y= mean, group = Site))+ geom_errorbar(aes(ymax = mean+se, ymin = mean-se, width= 0.5), position= position_dodge(0.5))+ geom_line(position= position_dodge(0.5), size=0.25, show.legend = FALSE)+ xlab("Zone")+ylab("Proportion Crustacean")+ facet_grid(col= vars(Species))+  scale_x_discrete(labels=c("High", "Mid", "Low"))+ theme(axis.text.x = element_text(angle = 45, vjust = 0.75))  +geom_point(stat="identity", position= position_dodge(width = 0.5), aes(fill = Species, shape = Site), size = 4, show.legend = FALSE) + theme_better + scale_shape_manual(values = c(22, 25)) + scale_fill_manual(values = c("white", "black"), labels = c("Zj","Zm")) + guides(fill=guide_legend(override.aes=list(shape=21))) + ylim(c(0.1,1))
plot(g_tot)
ggsave("figures/crust.mono.2.pdf", width = 6, height = 4.27)
```

```{r}
library(esc)

crust_mean<- epifauna%>%
  group_by(`Site`,`Zone`, `Species`, `Condition`)%>%
  summarise(mean = mean(crustacean, na.rm = T), n = length(crustacean)-sum(is.na(crustacean)), 
            sd = sd(crustacean, na.rm = T), se= sd/sqrt(n) )

tot.mean.mix <- tot_mean %>% filter(Condition == "Mix")
colnames(tot.mean.mix) <- c("Site", "Zone", "Species", "Condition", "mix.mean", 
             "mix.n", "mix.sd", "mix.se")
tot.mean.mono <- tot_mean %>% filter(Condition == "Mono")
colnames(tot.mean.mono) <- c("Site", "Zone", "Species", "Condition", "mono.mean", 
             "mono.n", "mono.sd", "mono.se")
tot.effect.df <- merge(tot.mean.mix, tot.mean.mono, by = c("Site", "Zone", "Species"))


tot.effect<- esc_mean_sd(grp1m = tot.effect.df$mono.mean, grp2m = tot.effect.df$mix.mean,
            grp1sd = tot.effect.df$mono.sd, grp2sd = tot.effect.df$mix.sd, 
            grp1n = tot.effect.df$mono.n, grp2n = tot.effect.df$mix.n)

#comp_mean<- effect.size %>%
  #group_by(`Site`,`Zone`, `Species.Comp`, `Species`)%>%
  #summarise(mean = mean(GRAMS, na.rm = T), n = length(GRAMS)-sum(is.na(GRAMS)), 
            #sd = sd(GRAMS, na.rm = T), se= sd/sqrt(n) )


e.size <- cbind(tot.effect.df, "Effect.size" = tot.effect$es, "Weight" = tot.effect$w, "Lower.CI" = tot.effect$ci.lo, "Upper.CI" = tot.effect$ci.hi)
e.size


efect.g<- ggplot(data.frame(e.size), aes(x=Zone, y= Effect.size, group = Species))+geom_point(stat="identity", position= position_dodge(width = 0.5), aes(shape = Species), size = 2)+ geom_errorbar(aes(ymax = Effect.size+se, ymin = Effect.size-se, width= 0.5), position= position_dodge(0.5))+ geom_line(position= position_dodge(0.5), size=0.25, show.legend = FALSE)+ xlab("Zone")+ylab("Effect Size")+ facet_grid(col= vars(Site))+  scale_x_discrete(labels=c("High", "Mid", "Low"))+ theme(axis.text.x = element_text(angle = 45, vjust = 0.75)) + scale_shape_manual(values= c(1,16), labels = c("Zj","Zm"))+ theme_better +geom_hline(yintercept=0, linetype="dashed", color = "red")
plot(efect.g)

ggsave("figures/crust.es.pdf", width = 6.92, height = 4.27)
```

```{r}
e.size$Species <- factor(e.size$Species, levels = c("ZJ", "ZM"), labels = c("Non-native", "Native")) 

efect.g<- ggplot(data.frame(e.size), aes(x=Zone, y= -(Effect.size), group = Site))+ geom_errorbar(aes(ymax = -(Upper.CI), ymin = -(Lower.CI), width= 0.5), position= position_dodge(0.5))+ geom_line(position= position_dodge(0.5), size=0.25, show.legend = FALSE)+ xlab("Zone")+ylab("Effect Size")+ facet_grid(col= vars(Species))+  scale_x_discrete(labels=c("High", "Mid", "Low"))+ theme(axis.text.x = element_text(angle = 45, vjust = 0.75)) + theme_better +geom_hline(yintercept=0, linetype="dashed", color = "red") +geom_point(stat="identity", position= position_dodge(width = 0.5), aes(shape = Site, fill = Species), size = 4, show.legend = FALSE) + ylim(c(-5.5, 3)) + scale_shape_manual(values = c(22, 25)) +  scale_fill_manual(values = c("white", "black")) 
plot(efect.g) 

ggsave("figures/crust.es.2.pdf", width = 6, height = 4.27)
```