---
title: "FR_epiphytes"
author: "Maria Garcia"
date: "2024-02-22"
output: html_document
---

```{r}
source("library.R")
```

```{r}
epiphytes<- read.csv("data/EPH.csv")
epiphytes<- separate(epiphytes, col=site, into=c( 'Site','Zone', 'Number', 'Species'))
epiphytes$Zone <- factor(epiphytes$Zone, levels = c("H", "M", "L"))

eph.mono <- filter(epiphytes, Condition == "monoculture")
eph.mono.anova<- aov(log(Standardized)~Site*Zone*Species, data = eph.mono)
summary(eph.mono.anova)

eph.zm <- filter(epiphytes, Species == "ZM")
eph.zm.anova<- aov(log(Standardized)~Site*Zone*Condition, data = eph.zm)
summary(eph.zm.anova)

eph.zj <- filter(epiphytes, Species == "ZJ")
eph.zj.anova.l<- aov(log(Standardized+0.06250000)~Site*Zone*Condition, data = eph.zj)
summary(eph.zj.anova.l)

```

Checking with emmeans
```{r}
sp.mono<-filter(eph.mono, Site == "SP")
eph.sp<-aov(Standardized~Zone * Species, data =sp.mono)
#summary(eph.sp)
# eph.comp<- emmeans(eph.sp, specs = pairwise~ Zone|Species)
# summary(eph.comp)

eph.comp<- emmeans(eph.sp, specs = pairwise~ Species|Zone)
summary(eph.comp)

sv.mono<-filter(eph.mono, Site == "SV")
eph.sv<-aov(Standardized~Zone * Species, data =sv.mono)
#summary(eph.sv)
# eph.comp<- emmeans(eph.sv, specs = pairwise~Zone|Species)
# summary(eph.comp)

eph.comp<- emmeans(eph.sv, specs = pairwise~Species|Zone)
summary(eph.comp)
```


```{r}
sph.mono <- filter(eph.mono, Site == "SP" & Zone == "H")
sph <- t.test(Standardized ~ Species, data = sph.mono)
sph 

spm.mono <- filter(eph.mono, Site == "SP" & Zone == "M")
spm <-  t.test(Standardized ~ Species, data = spm.mono)
spm

spl.mono <- filter(eph.mono, Site == "SP" & Zone == "L")
spl <- t.test(Standardized ~ Species, data = spl.mono)
spl


svh.mono <- filter(eph.mono, Site == "SV" & Zone == "H")
svh <- t.test(Standardized ~ Species, data = svh.mono)
svh

svm.mono <- filter(eph.mono, Site == "SV" & Zone == "M")
svm <- t.test(Standardized ~ Species, data = svm.mono)
svm

svl.mono<- filter(eph.mono, Site == "SV" & Zone == "L")
svl <-t.test(Standardized ~ Species, data = svl.mono)
svl
```
  
  Graphs 
    this has points 
```{r}
eph<-epiphytes %>%
  unite("Species.Comp", Species:Condition)
epiphytes.2 <- cbind(eph, Species=epiphytes$Species)
epiphytes.2$Species.Comp <- factor(epiphytes.2$Species.Comp, levels =c('ZJ_monoculture', 'ZJ_mixture', 'ZM_mixture', 'ZM_monoculture') )
epiphytes.2$Zone <- factor(epiphytes.2$Zone, levels =c('H', 'M', 'L') )

Species.labels<-  c("Non-native (Zj)", "Native (Zm)")
names(Species.labels)<- c("ZJ", "ZM")
Site.labels<-  c("SP (steep)", "SV (flat)")
names(Site.labels)<- c("SP", "SV")

eph_mean<- epiphytes.2 %>%
  group_by(`Site`,`Zone`, `Species.Comp`, `Species`)%>%
  summarise(mean = mean(Standardized, na.rm = T), n = length(Standardized)-sum(is.na(Standardized)), 
            sd = sd(Standardized, na.rm = T), se= sd/sqrt(n) )

g_eph<- ggplot(eph_mean, aes(x=Zone, y= mean, group = Species.Comp))+geom_point(stat="identity", position= position_dodge(width = 0.5), aes(shape = Species.Comp), size = 2)+ geom_errorbar(aes(ymax = mean+se, ymin = mean-se, width= 0.5), position= position_dodge(0.5))+ geom_line(position= position_dodge(0.5), size=0.25, aes(linetype=Species.Comp), show.legend = FALSE)+ xlab("Zone")+ylab("Epiphyte Load per Dry Mass of Eelgrass (g)")+ facet_grid(col= vars(Site), row = vars(Species))+  scale_x_discrete(labels=c("High", "Mid", "Low"))+ theme(axis.text.x = element_text(angle = 45, vjust = 0.75)) + scale_shape_manual(values= c(1,2,17,16), name = "Species Composition", labels = c("Zj monoculture","Zj mixture", "Zm mixture",  "Zm monoculture"))+   scale_linetype_manual(values=c("solid", "dashed", "dashed","solid"))+theme_better
plot(g_eph)
```



```{r}


Site.labels<-  c("SP (steep)", "SV (flat)")
names(Site.labels)<- c("SP", "SV")

eph_mono_mean<- eph.mono%>%
  group_by(`Site`,`Zone`, `Species`)%>%
  summarise(mean = mean(Standardized, na.rm = T), n = length(Standardized)-sum(is.na(Standardized)), 
            sd = sd(Standardized, na.rm = T), se= sd/sqrt(n) )
eph_mono_mean$Zone <- factor(eph_mono_mean$Zone, levels =c('H', 'M', 'L') )



g_eph<- ggplot(eph_mono_mean, aes(x=Zone, y= mean, group = Species))+ geom_errorbar(aes(ymax = mean+se, ymin = mean-se, width= 0.5), position= position_dodge(0.5))+ geom_line(position= position_dodge(0.5), size=0.25, show.legend = FALSE)+geom_point(stat="identity", position= position_dodge(width = 0.5), aes(fill = Species, shape = Species), size =4, show.legend = FALSE)+ xlab("Zone")+ylab("Epiphyte Load")+ facet_grid(col= vars(Site), labeller = labeller(Site = Site.labels))+  scale_x_discrete(labels=c("High", "Mid", "Low"))+ theme(axis.text.x = element_text(angle = 45, vjust = 0.75)) + scale_shape_manual(values= c(1,16), name = "Species Composition", labels = c("Zj monoculture","Zm monoculture"))+ theme_better + scale_fill_manual(values = c("white", "black"), labels = c("Zj","Zm"))  + scale_shape_manual(values = c(22, 25))
plot(g_eph)

ggsave("figures/eph.mono.pdf",  width = 6.92, height = 4.27)
```

```{r}


eph_mono_mean$Species <- factor(eph_mono_mean$Species, levels = c("ZJ", "ZM"), labels = c("Non-native", "Native"))
g_eph<- ggplot(eph_mono_mean, aes(x=Zone, y= mean, group = Site))+ geom_errorbar(aes(ymax = mean+se, ymin = mean-se, width= 0.5), position= position_dodge(0.5))+ geom_line(position= position_dodge(0.5), size=0.25, show.legend = FALSE)+ xlab("Zone")+ylab("Epiphyte Load")+ facet_grid(col= vars(Species))+  scale_x_discrete(labels=c("High", "Mid", "Low"))+ theme(axis.text.x = element_text(angle = 45, vjust = 0.75))  +geom_point(stat="identity", position= position_dodge(width = 0.5), aes(fill = Species, shape = Site), size = 4, show.legend = FALSE) + theme_better + scale_shape_manual(values = c(22, 25)) + scale_fill_manual(values = c("white", "black"), labels = c("Zj","Zm") ) + guides(fill=guide_legend(override.aes=list(shape=21)))
plot(g_eph)

ggsave("figures/eph.mono.2.pdf",  width = 6, height = 4.27)
```

```{r}
library(esc)

eph_mean<- epiphytes%>%
  group_by(`Site`,`Zone`, `Species`, `Condition`)%>%
  summarise(mean = mean(Standardized, na.rm = T), n = length(Standardized)-sum(is.na(Standardized)), 
            sd = sd(Standardized, na.rm = T), se= sd/sqrt(n) )

eph.mean.mix <- eph_mean %>% filter(Condition == "mixture")
colnames(eph.mean.mix) <- c("Site", "Zone", "Species", "Condition", "mix.mean", 
             "mix.n", "mix.sd", "mix.se")
eph.mean.mono <- eph_mean %>% filter(Condition == "monoculture")
colnames(eph.mean.mono) <- c("Site", "Zone", "Species", "Condition", "mono.mean", 
             "mono.n", "mono.sd", "mono.se")
eph.effect.df <- merge(eph.mean.mix, eph.mean.mono, by = c("Site", "Zone", "Species"))


eph.effect<- esc_mean_sd(grp1m = eph.effect.df$mono.mean, grp2m = eph.effect.df$mix.mean,
            grp1sd = eph.effect.df$mono.sd, grp2sd = eph.effect.df$mix.sd, 
            grp1n = eph.effect.df$mono.n, grp2n = eph.effect.df$mix.n)


#comp_mean<- effect.size %>%
  #group_by(`Site`,`Zone`, `Species.Comp`, `Species`)%>%
  #summarise(mean = mean(GRAMS, na.rm = T), n = length(GRAMS)-sum(is.na(GRAMS)), 
            #sd = sd(GRAMS, na.rm = T), se= sd/sqrt(n) )

e.size <- cbind(eph.effect.df, "Effect.size" =eph.effect$es, "Weight" = eph.effect$w, "Lower.CI" = eph.effect$ci.lo, "Upper.CI" = eph.effect$ci.hi)
e.size


```



```{r}
efect.g<- ggplot(data.frame(e.size), aes(x=Zone, y= -(Effect.size), group = Species))+ geom_errorbar(aes(ymax = -(Upper.CI), ymin = -(Lower.CI), width= 0.5), position= position_dodge(0.5))+ geom_line(position= position_dodge(0.5), size=0.25, show.legend = FALSE)+ xlab("Zone")+ylab("Effect Size")+ facet_grid(col= vars(Site))+  scale_x_discrete(labels=c("High", "Mid", "Low"))+ theme(axis.text.x = element_text(angle = 45, vjust = 0.75)) +geom_point(stat="identity", position= position_dodge(width = 0.5), aes(fill = Species), shape =21, size = 4 ) + theme_better +geom_hline(yintercept=0, linetype="dashed", color = "red")+ ylim(c(-5.5, 3)) +  scale_fill_manual(values = c("white", "black"), labels = c("Zj","Zm"))
plot(efect.g)

ggsave("figures/eph.es.pdf",width = 6.92, height = 4.27 )
```


```{r}
Species.labels<-  c("Non-native (Zj)", "Native (Zm)")
names(Species.labels)<- c("Non-native", "Native")
efect.g<- ggplot(data.frame(e.size), aes(x=Zone, y= -(Effect.size), group = Site))+ geom_errorbar(aes(ymax = -(Upper.CI), ymin = -(Lower.CI), width= 0.5), position= position_dodge(0.5))+ geom_line(position= position_dodge(0.5), size=0.25, show.legend = FALSE)+ xlab("Zone")+ylab("Effect Size")+ facet_grid(col= vars(Species), labeller = labeller(Species = Species.labels))+  scale_x_discrete(labels=c("High", "Mid", "Low"))+ theme(axis.text.x = element_text(angle = 45, vjust = 0.75)) + theme_better +geom_hline(yintercept=0, linetype="dashed", color = "red") +geom_point(stat="identity", position= position_dodge(width = 0.5), aes(shape = Site, fill = Species), size = 4,show.legend = FALSE) + ylim(c(-5.5, 3)) + scale_shape_manual(values = c(22, 25)) +  scale_fill_manual(values = c("white", "black")) 
plot(efect.g) 

ggsave("figures/eph.es.2.pdf", width = 6, height = 4.27)
```


```{r}

efect.g<- ggplot(data.frame(e.size), aes(x=Zone, y= -(Effect.size), group = Site))+ geom_errorbar(aes(ymax = -(Upper.CI), ymin = -(Lower.CI), width= 0.5), position= position_dodge(0.5))+ geom_line(position= position_dodge(0.5), size=0.25, show.legend = FALSE)+ xlab("Zone")+ylab("Effect Size")+ facet_grid(row= vars(Species))+  scale_x_discrete(labels=c("High", "Mid", "Low"))+ theme(axis.text.x = element_text(angle = 45, vjust = 0.75)) + theme_better +geom_hline(yintercept=0, linetype="dashed", color = "red") +geom_point(stat="identity", position= position_dodge(width = 0.5), aes(shape = Site, fill = Species), size = 4, show.legend = FALSE) + ylim(c(-5.5, 3)) + scale_shape_manual(values = c(22, 25)) +  scale_fill_manual(values = c("white", "black")) 
plot(efect.g) 

ggsave("figures/eph.es.3.pdf", width = 4.27, height = 6.92)
```

