---
title: "Non-Native"
author: "Maria Garcia"
date: '2023-04-02'
output: html_document
---

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(vegan)
library(grid)
library(lattice)
library(tibble)
library(cowplot)
library(gridExtra)
```



```{r}
non.native <- read.csv("functional.epifauna.csv")

non.native<- separate(non.native, col=Site, into=c( 'Site','Zone', 'Number', 'Species'))


non.mono <- filter(non.native, Condition == "Mono")
non.mono.anova<- aov(asin(sqrt(Invasive))~Site*Zone*Species, data = non.mono)
summary(non.mono.anova)


non.zm <- filter(non.native, Species == "ZM")
non.zm.anova<- aov(asin(sqrt(Invasive))~Site*Zone*Condition, data = non.zm)
summary(non.zm.anova)


non.zj <- filter(non.native, Species == "ZJ")
non.zj.anova<- aov(asin(sqrt(Invasive))~ Site*Zone*Condition, data = non.zj)
summary(non.zj.anova)

```

```{r}
non_mono_mean<- non.mono%>%
  group_by(`Site`,`Zone`, `Species`)%>%
  summarise(mean = mean(Invasive, na.rm = T), n = length(Invasive)-sum(is.na(Invasive)), 
            sd = sd(Invasive, na.rm = T), se= sd/sqrt(n) )
Site.labels<-  c("SP (steep)", "SV (flat)")
names(Site.labels)<- c("SP", "SV")
g_non<- ggplot(non_mono_mean, aes(x=Zone, y= mean, group = Species))+ geom_errorbar(aes(ymax = mean+se, ymin = mean-se, width= 0.5), position= position_dodge(0.5))+ geom_line(position= position_dodge(0.5), size=0.25, show.legend = FALSE)+ xlab("Zone")+ylab("Proportion of Non-Native Species ")+ facet_grid(col= vars(Site), labeller = labeller(Site = Site.labels))+  scale_x_discrete(labels=c("High", "Mid", "Low"))+ theme(axis.text.x = element_text(angle = 45, vjust = 0.75)) + scale_fill_manual(values = c("white", "black"), labels = c("Zj","Zm")) +geom_point(stat="identity", position= position_dodge(width = 0.5), aes(fill = Species, shape = Site), size = 4, )  + scale_shape_manual(values = c(22, 25)) + theme_better
plot(g_non)
ggsave("figures/non.mono.A.pdf", width = 6.92, height = 4.27)
```





